variables:
 DOCKER_HOST: tcp://localhost:2375
 DOCKER_DRIVER: overlay2
 CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
 CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

image: docker:18-dind

services:
  - docker:18-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - release

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE -f Dockerfile .
    - docker push $CONTAINER_TEST_IMAGE # Pushing to our registry for development. We can download image from registry

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only: # release-image step will be performed only on master branch
    - master
