name: mpe
channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - python=3.7
  - pandas=1.3.5
  - clustalo=1.2.4
  - holoviews=1.14.6
  - umap-learn=0.5.1
  - pytables>3.5.1
  - pynndescent=0.5.4
  - biopython=1.78
  - jupyterlab=3.2.4 
  - seaborn=0.11.2
  - datashader=0.13.0
  - bokeh=2.4.3
  - matplotlib=3.5.3
  - psutil=5.9.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - tqdm=4.64
  