name: pub
channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - biopython=1.77
  - bokeh=2.3.0
  - clustalo=1.2.4
  - datashader=0.12.1
  - holoviews=1.14
  - ipython
  - joblib=1.0.1
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyterlab
  - markdown
  - matplotlib=3.3.0
  - nbclient
  - nbconvert
  - nbformat
  - nbstripout
  - numba
  - pandas=1.2.3
  - python=3.7
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - seaborn=0.11.0
  - pytables=3.6.1
  - pynndescent=0.4.7
  - tqdm=4.45.0
  - umap-learn=0.5.1