name: pub
channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - biopython=1.77
  - bokeh=2.0.1
  - clustalo=1.2.4
  - datashader=0.10
  - holoviews=1.14
  - ipython
  - joblib
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyterlab
  - markdown
  - matplotlib=3.3.0
  - nbclient
  - nbconvert
  - nbformat
  - nbstripout
  - numba
  - pandas
  - python=3.7
  - scikit-learn=0.23.1
  - scipy
  - seaborn
  - pytables=3.6
  - pynndescent=0.4.7
  - tqdm
  - umap-learn=0.5.1